try {
    // console.log(name);
    console.log(getName()
    
} catch (error) {
    console.log("Error in catch block", error);
}
